version: '3.7'

services:

  api:
    container_name: solartesttask-api
    build:
      context: .
      dockerfile: SolarTestTask lvl5/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__PostgresBoardDb=Server=postgres;Database=Board;Username=postgres;Password=admin;Port=5433
    networks:
      - solarlab-academy-network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "Board"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - solarlab-academy-network

  
volumes:
  pg-data:
  
networks:
  solarlab-academy-network: